<?php

use Drupal\kifitos\AgreementConfigInterface;

function kifitos_kifitos_config_presave(AgreementConfigInterface $config) {
  Drupal::service('kifitos.agreement_resolver')->cacheConfigs([$config]);
}

function kifitos_rebuild() {
  $storage = Drupal::service('entity_type.manager')->getStorage('kifitos_config');
  $configs = $storage->loadMultiple();
  Drupal::service('kifitos.agreement_resolver')->cacheConfigs($configs);
}
